# Basic Information 
title: Zhengning Hu
position: Postdoctoral Research Associate
affiliation: The University of Arizona
email: zhengninghu (at) arizona.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Zhengning Hu
description: This is the academic personal homepage for Zhengning Hu.
canonical: https://zhengninghu.github.io/

# Links 
# If you don't need one of them, you may delete the corresponding line.
# google_scholar: https://scholar.google.com/
# cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/zhengninghu
# linkedin: https://www.linkedin.com/

# Images (e.g., your profile picture and your website's favicon) 
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively. 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: false

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"
